#!/usr/bin/env python3
"""
Convert a video into 128×64 Otsu B/W frame data (optional offline tool).

The Raspberry Pi OLED Dashboard plays video live with the same Otsu pipeline
inside oled_dashboard.py — you usually do not need this on the Pi.

Useful for:
  - previewing binary frames
  - packing frames for constrained devices
  - exporting a C header for other firmwares

Usage:
  python tools/video_to_frames.py path/to/clip.mp4
  python tools/video_to_frames.py clip.mp4 -o frames_data.h
"""

from __future__ import annotations

import argparse
from pathlib import Path

import cv2

WIDTH = 128
HEIGHT = 64
DEFAULT_FRAME_DELAY_MS = 16


def convert_video(video_path: Path, output_file: Path, frame_delay_ms: int) -> int:
    cap = cv2.VideoCapture(str(video_path))
    if not cap.isOpened():
        raise SystemExit(f"Could not open video: {video_path}")

    frames_list: list[list[str]] = []
    print("Extracting frames with Otsu thresholding (128×64)...")

    while True:
        ret, frame = cap.read()
        if not ret:
            break

        frame_res = cv2.resize(frame, (WIDTH, HEIGHT), interpolation=cv2.INTER_AREA)
        gray = cv2.cvtColor(frame_res, cv2.COLOR_BGR2GRAY)
        _, binary = cv2.threshold(gray, 0, 255, cv2.THRESH_BINARY | cv2.THRESH_OTSU)

        flat = binary.flatten()
        byte_array: list[str] = []
        for i in range(0, len(flat), 8):
            byte_val = 0
            for bit in range(8):
                if flat[i + bit] > 0:
                    byte_val |= 1 << (7 - bit)
            byte_array.append(f"0x{byte_val:02x}")
        frames_list.append(byte_array)

    cap.release()

    num_frames = len(frames_list)
    if num_frames == 0:
        raise SystemExit("No frames extracted")

    bytes_per_frame = (WIDTH * HEIGHT) // 8
    print(f"Writing {num_frames} frames → {output_file}")

    with open(output_file, "w", encoding="utf-8") as f:
        f.write("#pragma once\n")
        f.write("// Generated by tools/video_to_frames.py\n\n")
        f.write(f"#define FRAME_WIDTH {WIDTH}\n")
        f.write(f"#define FRAME_HEIGHT {HEIGHT}\n")
        f.write(f"#define FRAME_DELAY {frame_delay_ms}\n")
        f.write(f"#define NUM_FRAMES {num_frames}\n\n")
        f.write(
            f"const unsigned char frames[{num_frames}][{bytes_per_frame}] = {{\n"
        )
        for i, frame_bytes in enumerate(frames_list):
            f.write(f"  {{ // Frame {i}\n    ")
            lines = [
                ", ".join(frame_bytes[j : j + 16])
                for j in range(0, len(frame_bytes), 16)
            ]
            f.write(",\n    ".join(lines))
            f.write("\n  }" + ("," if i < num_frames - 1 else "") + "\n")
        f.write("};\n")

    print("Done.")
    return num_frames


def main() -> None:
    p = argparse.ArgumentParser(description="Video → 128×64 Otsu frame header")
    p.add_argument("video", type=Path, help="Input video path")
    p.add_argument(
        "-o",
        "--output",
        type=Path,
        default=Path("frames_data.h"),
        help="Output C header (default: frames_data.h)",
    )
    p.add_argument(
        "--delay",
        type=int,
        default=DEFAULT_FRAME_DELAY_MS,
        help="Frame delay ms metadata (default: 16)",
    )
    args = p.parse_args()
    convert_video(args.video, args.output, args.delay)


if __name__ == "__main__":
    main()
